### ISSUE TITLE
className property not passed through

### ISSUE THREAD

**Issue by csdietrich** [ertanhasani/react-stars#12]
I'm passing in the className property, but when it gets rendered it doesn't show up:

In code:
`className={"something"}`

Rendered:
`<div tabindex="0" aria-label="blah blah..." class="undefined react-stars"`

**Comment by ertanhasani** [comment]
If you look at the documentation, `className` is of type `string`, and you need to pass it as `className="some-class-name"`

**Comment by csdietrich** [comment]
Yes. I tried that too and still the same results.

**Comment by csdietrich** [comment]
I forked your codesandbox example. Added a className of "blahhh".

https://codesandbox.io/s/busy-robinson-mvo8d
