### ISSUE TITLE
onChange isn't working for me, unsure why

### ISSUE THREAD

**Issue by A-PS1999** [ertanhasani/react-stars#21]
I am trying to use this component in my React app but for some reason, despite trying to follow the examples provided (with a few changes for the sake of my app), I can't seem to get the `onChange` part of the component to do anything. That is to say, I click on the stars on the rendered page but nothing shows up in the console. There is no error message anywhere concerning the function or the component; things just don't seem to happen at all.

I will admit that I am pretty new to using React generally so it may be an oversight on my part with React. Nevertheless, I would appreciate help on how I can get this component to work.

Here's a rough and concise version of what part of my app looks like where I am trying to implement this component:

    `import ReactStars from 'react-rating-stars-component';
    
    class NewReview extends Component {

        ratingChange = (newRating) => {
            console.log(newRating)
        };

        constructor(props) {
            super(props)
            this.ratingToState = this.ratingToState.bind(this)
        }

        render() {
            return (
                <div className="container-fluid mt-5">
			    <div className="row">
				    <main role="main" className="col-lg-12 ml-auto mr-auto" style={{ maxWidth: '500px' }}>
					    <Container className="content mr-auto ml-auto">
						    <Row className="justify-content-md-center">
                                                            <Form onSubmit={(event) => {stuff}}>
                                                            <Form.Group>
                                                                <h4>Rating</h4>
                                                                <Rating onChange={this.ratingChange} />
                                                            </Form>
                                                 </Row>
                                         </Container>
                                  </main>
                         </div>
                </div>
               );
         }
    }
    
    const Rating = ({ratingChange}) => (
        <ReactStars size={60} onChange={ratingChange} />
    )

    export default NewReview;`

**Comment by blpraveen** [comment]
Have tried like this, it works onChange={(rating) => {this.rating = rating}}
