### ISSUE TITLE
can you pass a variable instead of a number in value prop 

### ISSUE THREAD

**Issue by BrianRigii** [ertanhasani/react-stars#4]
var  numStars = 3.5

> `<ReactStars`

                 ` count={5}
                  onChange={this.ratingChanged}
                  size={23}
                  isHalf={true}
                  emptyIcon={<i className="far fa-star"></i>}
                  halfIcon={<i className="fa fa-star-half-alt"></i>}
                  fullIcon={<i className="fa fa-star"></i>}
                  activeColor="red"
                  value={numStars}
                  color="#999999"`
                />`

im getting an error 
index.js:1 Warning: Failed prop type: Invalid prop `value` of type `string` supplied to `ReactStars`, expected `number`

**Comment by ertanhasani** [comment]
That should work. Please make sure you are not setting a string as a value to `numStars` somewhere else. If you still keep experiencing this error, reopen this issue and please provide a codesandbox link that I can see why is that happening.
