### ISSUE TITLE
custom star element doesn't work

### ISSUE THREAD

**Issue by nasserghiasi** [ertanhasani/react-stars#9]
I can't believe this package wasted my time. this component completely ignores emptyIcon and filledIcon props

**Comment by cristiancs** [comment]
It works but you need to specify the emptyIcon and filledIcon

**Comment by ertanhasani** [comment]
This does not ignore `emptyIcon` and `filledIcon` at all! If it does, can you please share code from your examples so we look further? Otherwise, by providing the `emptyIcon` and `filledIcon` you are able to set your own icons!
